
TYPO3:
  TYPO3CR:
    Search:
      realtimeIndexing:
        enabled: true
      indexingBatchSize: 100
      defaultConfigurationPerType:
        string:
          indexing: '${value}'
        boolean:
          indexing: '${value}'
        integer:
          indexing: '${value}'
        date:
          indexing: '${(value ? value.format(''Y-m-d\TH:i:s'') + ''Z'' : null)}'
        TYPO3\Media\Domain\Model\Video:
          indexing: ''
        TYPO3\Media\Domain\Model\ImageVariant:
          indexing: ''
        references:
          indexing: '${Indexing.convertArrayOfNodesToArrayOfNodeIdentifiers(value)}'
        reference:
          indexing: '${value.identifier}'
      defaultContext:
        String: TYPO3\Eel\Helper\StringHelper
        Array: TYPO3\Eel\Helper\ArrayHelper
        Date: TYPO3\Eel\Helper\DateHelper
        Indexing: TYPO3\TYPO3CR\Search\Eel\IndexingHelper
  TypoScript:
    defaultContext:
      Search: TYPO3\TYPO3CR\Search\Eel\SearchHelper
