TYPO3:
  TYPO3CR:
    SearchCommons:
      indexingBatchSize: 100
      defaultConfigurationPerType:
        string:
          indexing: "${value}"

        boolean:
          indexing: "${value}"

        integer:
          indexing: "${value}"

        date:
          indexing: "${(value ? value.format('Y-m-d\\TH:i:s') + 'Z' : null)}"

        'TYPO3\Media\Domain\Model\Video':
          # deliberately don't map or index this
          indexing: ''

        'TYPO3\Media\Domain\Model\ImageVariant':
          # deliberately don't map or index this
          indexing: ''

        references:
          indexing: "${IndexingHelper.convertArrayOfNodesToArrayOfNodeIdentifiers(value)}"

        reference:
          indexing: "${value.identifier}"


      # Default context objects that are available in Eel expressions
      #
      # New variables should be added with a package key prefix. Example:
      #
      #   defaultContext:
      #     'MyPackage.String': 'MyPackage\Helper\StringHelper'
      #
      defaultContext:
        String: 'TYPO3\Eel\Helper\StringHelper'
        Array: 'TYPO3\Eel\Helper\ArrayHelper'
        Date: 'TYPO3\Eel\Helper\DateHelper'
        IndexingHelper: 'TYPO3\TYPO3CR\SearchCommons\Eel\IndexingHelper'

  TypoScript:
    defaultContext:
      Search: 'TYPO3\TYPO3CR\SearchCommons\Eel\SearchHelper'

  Flow:
    persistence:
      doctrine:
        eventListeners:
          'TYPO3\TYPO3CR\SearchCommons\EventListener\NodeDataEventListener':
            events: ['prePersist', 'preUpdate', 'preRemove', 'postFlush']
            listener: 'TYPO3\TYPO3CR\SearchCommons\EventListener\NodeDataEventListener'