TYPO3:
  TYPO3CR:
    Search:
      realtimeIndexing:
        enabled: TRUE

      # after how many entries should indexing occur at max?
      indexingBatchSize: 100

      defaultConfigurationPerType:
        string:
          indexing: "${value}"

        boolean:
          indexing: "${value}"

        integer:
          indexing: "${value}"

        date:
          indexing: "${(value ? Date.format(value, 'Y-m-d\\TH:i:s') + 'Z' : null)}"

        'TYPO3\Media\Domain\Model\Video':
          # deliberately don't map or index this
          indexing: ''

        'TYPO3\Media\Domain\Model\ImageInterface':
          # deliberately don't map or index this
          indexing: ''

        references:
          indexing: "${Indexing.convertArrayOfNodesToArrayOfNodeIdentifiers(value)}"

        reference:
          indexing: "${value.identifier}"


      # Default context objects that are available in Eel expressions
      #
      # New variables should be added with a package key prefix. Example:
      #
      #   defaultContext:
      #     'MyPackage.String': 'MyPackage\Helper\StringHelper'
      #
      defaultContext:
        String: 'Neos\Eel\Helper\StringHelper'
        Array: 'Neos\Eel\Helper\ArrayHelper'
        Date: 'Neos\Eel\Helper\DateHelper'
        Indexing: 'Neos\ContentRepository\Search\Eel\IndexingHelper'

  TypoScript:
    defaultContext:
      Search: 'Neos\ContentRepository\Search\Eel\SearchHelper'